title: Nixon Geno # your name (or website title) here
#logo: "/images/880077.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <h2>Data Scientist</h2>   
  Machine Learning | Artifical Intelligence | NLP | Computer Vision | Computer Graphics  
  <br><br>
  <a class="out" href="https://www.linkedin.com/in/nixon-geno">Contact Me</a> 
  <br><br>
  <style>footer,.view{display:none}</style>
theme: jekyll-theme-minimal
