title: Nixon Geno # your name (or website title) here
logo: "/images/880077.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <h2>Data Scientist</h2> 
  
  Second description 
  <br><br>
  <a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a> 
  <br><br>
  <style>footer{display:none}</style>
theme: jekyll-theme-minimal
